services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    ports:
      - "4822:4822"
    environment:
      GUACD_LOG_LEVEL: debug
    networks:
      - guacnet

  rdp:
    build:
      context: ./rdp
      args:
        RDP_USER: rdpuser
        RDP_PASSWORD: rdppass
    container_name: demo-rdp
    restart: unless-stopped
    ports:
      - "13389:3389"
    environment:
      - TZ=Asia/Tokyo
    networks:
      - guacnet

  ssh:
    build: ./ssh
    container_name: demo-ssh
    restart: unless-stopped
    ports:
      - "2222:22"
    environment:
      - TZ=Asia/Tokyo
      - SSH_USER=sshuser
      - SSH_PASSWORD=sshpass
    volumes:
      - demo-ssh-hostkeys:/etc/ssh/hostkeys
    networks:
      - guacnet
  
  telnet:
    build:
      context: ./telnet
      args:
        TELNET_USER: telnetuser
        TELNET_PASSWORD: telnetpass
    container_name: demo-telnet
    restart: unless-stopped
    ports:
      - "12323:23"
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge

volumes:
  demo-ssh-hostkeys:
